proyectodj/proyectodj/urls.py
from django.contrib import admin
from django.urls import path
from smartw import views

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('smt', views.smt),  
    path('show',views.show),  
    path('edit/<int:pk>', views.edit),  
    path('update/<int:pk>', views.update),  
    path('delete/<int:pk>', views.destroy),  
]  


proyectodj/smartw/models.py
from django.db import models

# Create your models here.
class Smartband(models.Model):
    auto_increment_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)   
    age = models.IntegerField()
    weight=models.IntegerField()
    heart_rate=models.IntegerField()
    BPM=models.IntegerField()
    Sp_o=models.IntegerField()
    level_stress=models.IntegerField()
class meta:
    db_table="smartband"


proyectodj/smartw/forms.py
from django import forms  
from smartw.models import Smartband  
class SmartbandForm(forms.ModelForm):  
    class Meta:  
        model = Smartband 
        fields = "__all__"  

proyectodj/smartw/views.py

from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect  
from smartw.forms import SmartbandForm  
from smartw.models import Smartband  
  
def smt(request):  
    if request.method == "POST":  
        form = SmartbandForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/show')  
            except:  
                pass  
    else:  
        form = SmartbandForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    smartw = Smartband.objects.all()  
    return render(request,"show.html",{'smartband':smartw})  
def edit(request, pk):  
    smartw = Smartband.objects.get(pk=pk)  
    return render(request,'edit.html', {'smartband':smartw})  
def update(request, pk):  
    smartw = Smartband.objects.get(pk=pk) 
    form = SmartbandForm(request.POST, instance = smartw)   
    if form.is_valid():  
        form.save()  
        return redirect("/show")  
    return render(request, 'edit.html', {'smartband': smartw})  
def destroy(request,pk):  
    smartw = Smartband.objects.filter(pk=pk)  
    smartw.delete()  
    return redirect("/show")  

proyectodj/smartw/templates/edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Index</title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
      
</head>  
<body>  
<form method="POST" class="post-form" action="/update/{{smartband.pk}}">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Actualizar</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nombre:</label>  
    <div class="col-sm-4">  
        <input type="text" name="name" id="id_name" required maxlength="20" value="{{ smartband.name }}"/>  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Edad:</label>  
    <div class="col-sm-4">  
        <input type="number" name="age" id="id_age" required maxlength="100" value="{{ smartband.age }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Peso:</label>  
    <div class="col-sm-4">  
        <input type="number" name="weight" id="id_weight" required maxlength="100" value="{{ smartband.weight }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Frecuencia cardiaca:</label>  
    <div class="col-sm-4">  
        <input type="number" name="heart_rate" id="id_heart_rate" required maxlength="254" value="{{ smartband.heart_rate }}" />  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Medida en BPM:</label>  
    <div class="col-sm-4">  
        <input type="number" name="BPM" id="id_BPM" required maxlength="15" value="{{ smartband.BPM }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Saturacion de oxigeno en sangre:</label>  
    <div class="col-sm-4">  
        <input type="number" name="Sp_o" id="id_Sp_o" required maxlength="15" value="{{ smartband.Sp_o }}" />  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nivel de stress:</label>  
    <div class="col-sm-4">  
        <input type="number" name="level_stress" id="id_level_stress" required maxlength="15" value="{{ smartband.level_stress }}" />  
    </div>  
  </div> 
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-success">Actualizar</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>

proyectodj/smartw/templates/index.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <title>Index</title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
     
</head>  
<body>  
<form method="POST" class="post-form" action="/smt">  
        {% csrf_token %}  
    <div class="container">  
<br>  
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <h3>Metricas de salud basicas</h3>  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nombre:</label>  
    <div class="col-sm-4">  
      {{ form.name }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Edad:</label>  
    <div class="col-sm-4">  
      {{ form.age }}  
    </div>  
  </div>  
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Peso:</label>  
    <div class="col-sm-4">  
      {{ form.weight }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Frecuencia cardiaca:</label>  
    <div class="col-sm-4">  
      {{ form.heart_rate }}  
    </div>  
  </div>  
    <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Medida en BPM:</label>  
    <div class="col-sm-4">  
      {{ form.BPM }}  
    </div>  
  </div>
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Saturacion de oxigeno en sangre:</label>  
    <div class="col-sm-4">  
      {{ form.Sp_o}}  
    </div> 
  </div> 
  <div class="form-group row">  
    <label class="col-sm-2 col-form-label">Nivel de stress:</label>  
    <div class="col-sm-4">  
      {{ form.level_stress}}  
    </div>  
   </div>    
    <div class="form-group row">  
    <label class="col-sm-1 col-form-label"></label>  
    <div class="col-sm-4">  
    <button type="submit" class="btn btn-primary">Submit</button>  
    </div>  
  </div>  
    </div>  
</form>  
</body>  
</html>  

proyectodj/smartw/templates/show.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>contacto</title>  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"> 
     
</head>  
<body>  
<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Nombre</th>  
        <th>Edad</th>  
        <th>Peso</th> 
        <th>Frecuencia cardiaca</th>  
        <th>Medida en BPM</th>  
        <th>Saturacion de oxigeno en sangre</th> 
        <th>Nivel de stress</th>
        <th>Actions</th> 
    </tr>  
    </thead>  
    <tbody>  
{% for smartband in smartband %}  
    <tr>  
        <td>{{ smartband.name}}</td>  
        <td>{{ smartband.age }}</td>  
        <td>{{ smartband.weight }}</td>  
        <td>{{ smartband.heart_rate }}</td>  
        <td>{{ smartband.BPM }}</td>  
        <td>{{ smartband.Sp_o }}</td>
        <td>{{ smartband.level_stress}}</td>

        <td>  
            <a href="/edit/{{ smartband.pk}}"><span class="glyphicon glyphicon-pencil" >Editar</span></a>  
            <a href="/delete/{{ smartband.pk }}">Eliminar</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/smt" class="btn btn-primary">Añadir</a></center>  
</body>  
</html>